/// Flutter icons AppIconClass
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIconClass
///      fonts:
///       - asset: fonts/AppIconClass.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIconClass {
  AppIconClass._();

  static const _kFontFam = 'AppIconClass';
  static const String? _kFontPkg = null;

  static const IconData lyrics =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lyrics_filled =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
